In [2]:
import numpy as np
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999],
      shape=(1000000,))

In [16]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]], dtype= np.float64)
print(data)
data*10
data + data
data.shape
data.dtype
data.ndim
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.bytes_)
numeric_strings.astype(float)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

array([ 1.25, -9.6 , 42.  ])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr
arr + arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
arr2d[0][2]

np.int64(3)

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot (arr, arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
samples
samples.mean()
arr.mean(axis=1)

array([ 0.33333333,  0.33333333,  3.66666667, -0.66666667,  0.66666667])

In [33]:
arr.sort(axis=0)
arr

array([[-2, -1,  0],
       [-1,  0,  0],
       [ 0,  1,  1],
       [ 1,  1,  2],
       [ 2,  3,  6]])

In [35]:
import pandas as pd
from pandas import Series, DataFrame

In [37]:
obj = pd.Series([4, 7, -5, 3])
obj
obj.index

RangeIndex(start=0, stop=4, step=1)

In [80]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2
obj2[obj2 > 2]
# obj2["c"]
# obj2.index
obj2 = obj2.reindex(["a", "b", "c", "d"])
obj2

a   -5
b    7
c    3
d    4
dtype: int64

In [48]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
data = {
    "order": range(5),
    "family": ["zezo", "awad", "ali", "hassan", "awad"]
}
df = pd.DataFrame(data)
df
# df = pd.DataFrame(data, columns=["order", "family"])
# df

   order  family
0      0    zezo
1      1    awad
2      2     ali
3      3  hassan
4      4    awad

In [72]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame
frame.year
frame.loc[2]
# frame.iloc[2]
frame.index.name = "id"
frame

     state  year  pop
id
0     Ohio  2000  1.5
1     Ohio  2001  1.7
2     Ohio  2002  3.6
3   Nevada  2001  2.4
4   Nevada  2002  2.9
5   Nevada  2003  3.2

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                        index=["Ohio", "Colorado", "Utah", "New York"],
                        columns=["one", "two", "three", "four"])
data
# data.drop(index=["Colorado", "Ohio"])
# data.drop(columns=["two"])
# data.drop(["two", "four"], axis=1)
# data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14